name: Build Yumi

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24'

      - name: Install WebUI dependencies
        working-directory: ./webui
        run: npm install

      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: aarch64-linux-android
          components: rust-src

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r29

      - name: Setup cargo-ndk
        run: |
          echo "ANDROID_NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV
          cargo install cargo-ndk

      - name: Install bpf-linker via cargo-binstall
        run: |
          cargo install cargo-binstall
          cargo binstall -y bpf-linker

      - name: Install system dependencies (clang, lld)
        run: |
          sudo apt-get update
          sudo apt-get install -y clang lld

      - name: Run xtask build
        run: cargo xtask build

      - name: Get Artifact Name
        id: artifact-name
        run: |
          FILE_PATH=$(ls output/*.zip | head -n 1)
          FILE_NAME=$(basename "$FILE_PATH")
          ARTIFACT_NAME="${FILE_NAME%.zip}"
          echo "name=$ARTIFACT_NAME" >> $GITHUB_OUTPUT
          echo "path=$FILE_PATH" >> $GITHUB_OUTPUT

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.artifact-name.outputs.name }}
          path: ${{ steps.artifact-name.outputs.path }}
